import React from 'react';
import { useParams } from 'react-router-dom';
import { ChatsView } from '../domains/chats/ChatsView';
import { SecurityCenterView } from '../domains/security/SecurityCenterView';
import { MediaVaultPage } from '../domains/media/MediaVaultPage';
import { StoriesPage as StoriesDomainPage } from '../domains/stories/StoriesPage';
import { LivePage as LiveDomainPage } from '../domains/live/LivePage';
import { TrustRoomsPage as TrustRoomsDomainPage } from '../domains/platform/TrustRoomsPage';
import { SubscriptionsPage as SubscriptionsDomainPage } from '../domains/platform/SubscriptionsPage';
import { ModerationPage as ModerationDomainPage } from '../domains/platform/ModerationPage';
import { AdminPage as AdminDomainPage } from '../domains/platform/AdminPage';
import { PresencePage as PresenceDomainPage } from '../domains/platform/PresencePage';
import { BattlesPage as BattlesDomainPage } from '../domains/platform/BattlesPage';

export const StoriesPage = () => <StoriesDomainPage />;
export const ChatsPage = () => <ChatsView />;
export const MediaPage = () => <MediaVaultPage />;
export const LivePage = () => { const { streamId } = useParams<{ streamId?: string }>(); return <LiveDomainPage streamId={streamId} />; };
export const TrustRoomsPage = () => <TrustRoomsDomainPage />;
export const SubscriptionsPage = () => <SubscriptionsDomainPage />;
export const SecurityPage = () => <SecurityCenterView />;
export const ModerationPage = () => <ModerationDomainPage />;
export const AdminPage = () => <AdminDomainPage />;
export const PresencePage = () => <PresenceDomainPage />;
export const BattlesPage = () => <BattlesDomainPage />;
