/** Server-backed cryptographic device registry. */
import React, { useEffect, useState } from 'react';
import { Laptop, ShieldCheck, Trash2, Plus, Fingerprint } from 'lucide-react';
import { Badge, Button, Dialog, Input } from '../../../shared/design-system/primitives';
import type { TrustedDevice } from '../../../shared/api/backendContracts';
import { SecurityService } from '../SecurityService';
import { cryptoApi } from '../../chats/api/cryptoApi';

export const DevicesSection: React.FC = () => {
  const [devices, setDevices] = useState<TrustedDevice[]>([]);
  const [isAddDeviceOpen, setIsAddDeviceOpen] = useState(false);
  const [newDeviceName, setNewDeviceName] = useState('');
  const [busy, setBusy] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);

  useEffect(() => {
    void SecurityService.getDevices().then(setDevices).catch((error) => setLoadError(error instanceof Error ? error.message : 'Unable to load devices.'));
    return SecurityService.subscribe((state) => setDevices(state?.devices ?? []));
  }, []);

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newDeviceName.trim()) return;
    setBusy(true);
    setLoadError(null);
    try {
      await cryptoApi.registerCurrentDevice(newDeviceName.trim());
      await SecurityService.getDevices();
      setNewDeviceName('');
      setIsAddDeviceOpen(false);
    } catch (error) {
      setLoadError(error instanceof Error ? error.message : 'Device registration failed.');
    } finally { setBusy(false); }
  };

  return (
    <div className="space-y-6">
      <div className="p-5 rounded-[var(--radius-2xl)] bg-surface border border-subtle flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="text-base font-extrabold text-primary flex items-center gap-2"><Fingerprint className="w-5 h-5 text-indigo-400" />Registered Devices & Cryptographic Identity</h2>
          <p className="text-xs text-tertiary mt-0.5">Device keys are generated by Web Crypto and private keys remain in IndexedDB as non-extractable CryptoKeys. The server controls registration and revocation.</p>
        </div>
        <Button onClick={() => setIsAddDeviceOpen(true)} variant="primary" size="sm" leftIcon={<Plus className="w-4 h-4" />}>Register This Browser</Button>
      </div>

      {loadError && <div role="alert" className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-200">{loadError}</div>}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {devices.map((dev) => (
          <div key={dev.id} className="p-5 rounded-[var(--radius-2xl)] bg-surface border border-subtle flex flex-col justify-between gap-4">
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div className="p-2.5 rounded-[var(--radius-xl)] bg-indigo-500/10 text-indigo-400"><Laptop className="w-5 h-5" /></div>
                <Badge variant={dev.trustStatus === 'VERIFIED' ? 'success' : 'warning'} size="sm">{dev.trustStatus.toUpperCase()}</Badge>
              </div>
              <div>
                <h3 className="text-sm font-bold text-primary">{dev.deviceName || 'GAPAK device'}</h3>
                <p className="text-[11px] text-tertiary font-mono mt-1 break-all">Identity fingerprint: {dev.fingerprint}</p>
              </div>
            </div>
            <div className="pt-3 border-t border-subtle flex items-center justify-between text-[11px] text-tertiary font-mono">
              <span>{new Date(dev.lastSeenAt ?? dev.createdAt).toLocaleString()}</span>
              {!dev.revokedAt && <button onClick={() => void SecurityService.revokeDevice(dev.id)} className="p-1 text-muted hover:text-rose-400" aria-label="Revoke device"><Trash2 className="w-4 h-4" /></button>}
            </div>
          </div>
        ))}
        {devices.length === 0 && <div className="md:col-span-3 p-8 rounded-[var(--radius-2xl)] border border-dashed border-default dark:border-default text-center text-sm text-muted">No registered cryptographic devices.</div>}
      </div>

      <Dialog isOpen={isAddDeviceOpen} onClose={() => setIsAddDeviceOpen(false)} title="Register This Browser">
        <form onSubmit={handleRegister} className="space-y-4">
          <Input label="Device label" value={newDeviceName} onChange={(e) => setNewDeviceName(e.target.value)} placeholder="e.g. My Windows Browser" required />
          <p className="text-xs text-muted">A fresh ECDH agreement key and ECDSA signing key will be generated locally. Private keys never leave this browser.</p>
          <div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setIsAddDeviceOpen(false)}>Cancel</Button><Button type="submit" variant="primary" isLoading={busy} leftIcon={<ShieldCheck className="w-4 h-4" />}>Generate & Register</Button></div>
        </form>
      </Dialog>
    </div>
  );
};
